Exception at 27-02-2025 : 15-52-58
.............................................
In custom_units.tcia_management
Message: Unexpected error while running TCIA files retrieve scheduler
Traceback :
 ............
Traceback (most recent call last):
  File "C:\Users\45422\Desktop\API_version\ThesisProject2\dicom_server\custom_units\tcia_management.py", line 38, in schedule_files_retrieval
    schedule_unit = getattr(schedule.every(self.period), self.period_unit)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Job' object has no attribute 'minuite'

Exception at 27-02-2025 : 15-53-52
.............................................
In custom_units.tcia_management
Message: Unexpected error while running TCIA files retrieve scheduler
Traceback :
 ............
Traceback (most recent call last):
  File "C:\Users\45422\Desktop\API_version\ThesisProject2\dicom_server\custom_units\tcia_management.py", line 38, in schedule_files_retrieval
    schedule_unit = getattr(schedule.every(self.period), self.period_unit)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Job' object has no attribute 'minuites'

Exception at 27-02-2025 : 15-54-19
.............................................
In custom_units.tcia_management
Message: Unexpected error while running TCIA files retrieve scheduler
Traceback :
 ............
Traceback (most recent call last):
  File "C:\Users\45422\Desktop\API_version\ThesisProject2\dicom_server\custom_units\tcia_management.py", line 38, in schedule_files_retrieval
    schedule_unit = getattr(schedule.every(self.period), self.period_unit)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Job' object has no attribute 'minuit'

Exception at 27-02-2025 : 15-54-38
.............................................
In custom_units.tcia_management
Message: Unexpected error while running TCIA files retrieve scheduler
Traceback :
 ............
Traceback (most recent call last):
  File "C:\Users\45422\Desktop\API_version\ThesisProject2\dicom_server\custom_units\tcia_management.py", line 38, in schedule_files_retrieval
    schedule_unit = getattr(schedule.every(self.period), self.period_unit)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Job' object has no attribute 'minuite'

Exception at 27-02-2025 : 15-55-29
.............................................
In schedule
Message: Unexpected error while running TCIA files retrieve scheduler
Traceback :
 ............
Traceback (most recent call last):
  File "C:\Users\45422\Desktop\API_version\ThesisProject2\dicom_server\custom_units\tcia_management.py", line 38, in schedule_files_retrieval
    schedule_unit = getattr(schedule.every(self.period), "minute")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\45422\AppData\Local\Programs\Python\Python311\Lib\site-packages\schedule\__init__.py", line 339, in minute
    raise IntervalError("Use minutes instead of minute")
schedule.IntervalError: Use minutes instead of minute

Exception at 27-02-2025 : 15-56-29
.............................................
In custom_units.tcia_management
Message: Unexpected error while running TCIA files retrieve scheduler
Traceback :
 ............
Traceback (most recent call last):
  File "C:\Users\45422\Desktop\API_version\ThesisProject2\dicom_server\custom_units\tcia_management.py", line 38, in schedule_files_retrieval
    schedule_unit = getattr(schedule.every(self.period), str(self.period_unit))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Job' object has no attribute 'minuites'

Exception at 27-02-2025 : 15-57-31
.............................................
In custom_units.tcia_management
Message: Unexpected error while running TCIA files retrieve scheduler
Traceback :
 ............
Traceback (most recent call last):
  File "C:\Users\45422\Desktop\API_version\ThesisProject2\dicom_server\custom_units\tcia_management.py", line 38, in schedule_files_retrieval
    schedule_unit = getattr(schedule.every(self.period), "minuites")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Job' object has no attribute 'minuites'

Exception at 27-02-2025 : 15-57-51
.............................................
In custom_units.tcia_management
Message: Unexpected error while running TCIA files retrieve scheduler
Traceback :
 ............
Traceback (most recent call last):
  File "C:\Users\45422\Desktop\API_version\ThesisProject2\dicom_server\custom_units\tcia_management.py", line 38, in schedule_files_retrieval
    schedule_unit = getattr(schedule.every(self.period), "minuite")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Job' object has no attribute 'minuite'

